# $NetBSD$

DISTNAME=	primesieve-5.4.2
CATEGORIES=	devel
MASTER_SITES=	http://dl.bintray.com/kimwalisch/primesieve/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://dl.bintray.com/kimwalisch/primesieve/
COMMENT=	C/C++ library that generates primes
LICENSE=	2-clause-bsd

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
